name: Remove-KeePassConfigTrigger
authors:
  - '@tifkin_'
  - '@harmj0y'
description: This module removes all triggers from all KeePass configs found by Find-KeePassConfig.
software: ''
techniques:
  - T1033
background: true
output_extension: ''
needs_admin: false
opsec_safe: false
language: powershell
min_language_version: '2'
comments:
  - https://github.com/adaptivethreat/KeeThief
options:
  - name: Agent
    description: Agent to run the module on.
    required: true
    value: ''
  - name: OutputFunction
    description: PowerShell's output function to use ("Out-String", "ConvertTo-Json", "ConvertTo-Csv", "ConvertTo-Html", "ConvertTo-Xml").
    required: false
    value: 'Out-String'
    strict: false
    suggested_values:
      - Out-String
      - ConvertTo-Json
      - ConvertTo-Csv
      - ConvertTo-Html
      - ConvertTo-Xml
script_path: 'empire/server/data/module_source/collection/vaults/KeePassConfig.ps1'
script_end: Get-Process *keepass* | Stop-Process -Force; Find-KeePassconfig | Remove-KeePassConfigTrigger | Format-List | {{ OUTPUT_FUNCTION }} | %{$_ + "`n"}; 'Remove-KeePassConfigTrigger completed'
